import Header from '@/app/Components/header'
import './globals.css'



export const metadata = {
  title: 'IMDb Clone Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header />
        
        {children}
      </body>
    </html>
  )
}
